# --- BASIC SITE META ---
title: Blogs, tutorials, and research notes
author: Filippo Maria Bianchi
# description: ""
url: "https://filippomb.github.io"
baseurl: "/blogs"          # <— important for project pages

# --- THEME ---
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"

# --- PLUGINS ---
plugins:
  - jekyll-include-cache   # optional but recommended

# --- COLLECTIONS ---
collections:
  tutorials:
    output: true
    permalink: /:title/

# (Optional) DEFAULTS → tell MM to render every _pages file with the “single” layout
defaults:
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single