# --- BASIC SITE META ---
title: Filippo Maria Bianchi's Blogs
author: Filippo Maria Bianchi
description: A collection of blogs, tutorials, and research notes by Filippo Maria Bianchi
url: "https://filippomb.github.io"
baseurl: "/blogs"

# --- THEME ---
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "contrast"

# --- FAVICON ---
favicon: "/assets/figs/favicon.svg"

# --- MATHJAX SCRIPTS ---
head_scripts:
  - /assets/js/mathjax_config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js

# --- PLUGINS ---
plugins:
  - jekyll-include-cache   # optional but recommended
markdown: kramdown
kramdown:
  math_engine: mathjax

# --- COLLECTIONS ---
collections:
  blogs:
    output: true
    permalink: /:title/
    
defaults:
  - scope:
      path: ""
      type: blogs
    values:
      layout: single
      toc: true
      toc_label: "Contents"
      mathjax: true