# --- BASIC SITE META ---
title: Filippo Maria Bianchi's Blogs
author: Filippo Maria Bianchi
description: A collection of blogs, tutorials, and research notes by Filippo Maria Bianchi
url: "https://filippomb.github.io"
baseurl: "/blogs"

# --- THEME ---
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: contrast

# --- PLUGINS ---
plugins:
  - jekyll-include-cache   # optional but recommended
markdown: kramdown
kramdown:
  math_engine: mathjax

# --- COLLECTIONS ---
collections:
  tutorials:
    output: true
    permalink: /:title/

# (Optional) DEFAULTS → tell MM to render every _pages file with the “single” layout
defaults:
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single
      toc: true
      toc_label: "Contents"
      mathjax: true